name: fidbek_flutter
description: Flutter plugin wrapper for Fidbek iOS/Android binary SDKs.
version: 0.1.3
homepage: https://fidbek.dev
repository: https://github.com/Saltware-Tech/fidbek-flutter
issue_tracker: https://github.com/Saltware-Tech/fidbek-flutter/issues

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.fidbek.flutter
        pluginClass: FidbekFlutterPlugin
      ios:
        pluginClass: FidbekFlutterPlugin
